rtemp = open("README.md", "w+")

rtemp.write("# Project Title\n")
rtemp.write("\n")
rtemp.write("## Description\n")
rtemp.write("What you should learn from this project:\n")
rtemp.write("\n")
rtemp.write("*\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("---\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")         
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("### [](./)\n")
rtemp.write("*\n")
rtemp.write("\n")
rtemp.write("---\n")
rtemp.write("\n")
rtemp.write("## Author\n")
rtemp.write("* **Derrick Gee** - [kai-dg](https://github.com/kai-dg)")
