h_putchar = open("_putchar.c", "w+")

h_putchar.write("#include <unistd.h>\n")
h_putchar.write("\n")
h_putchar.write("/**\n")
h_putchar.write(" * _putchar - writes the character c to stdout\n")
h_putchar.write(" * @c: The character to print\n")
h_putchar.write(" *\n")
h_putchar.write(" * Return: On success 1.\n")
h_putchar.write(" * On error, -1 is returned, and errno is set appropriately.\n")
h_putchar.write(" */\n")
h_putchar.write("int _putchar(char c)\n")
h_putchar.write("{\n")
h_putchar.write("	return (write(1, &c, 1));\n")
h_putchar.write("}")
